stages:
  - build
  - deploy
variables:
  IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
build_image:
  image: docker:stable
  services:
    - docker:dind
  stage: build
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker build -t $IMAGE_TAG .
    - docker push $IMAGE_TAG
  after_script:
    - docker logout ${CI_REGISTRY}
  only:
    - tags
    - master
    - develop
deploy:
  when: manual
  image: kroniak/ssh-client
  stage: deploy
  before_script:
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
    - echo "$ssh_deploy_key" > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
  script:
    - export > ./environment-$CI_COMMIT_SHA.env
    - sed -i 's/declare[[:space:]]-x/export/g' ./environment-$CI_COMMIT_SHA.env
    - scp -i ~/.ssh/id_rsa ./environment-$CI_COMMIT_SHA.env dockeruser@$ssh_deploy_host:~/environment-$CI_COMMIT_SHA.env
    - rm ./environment-$CI_COMMIT_SHA.env
    - ssh dockeruser@$ssh_deploy_host "source ./environment-$CI_COMMIT_SHA.env && docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY"
    - ssh dockeruser@$ssh_deploy_host "source ./environment-$CI_COMMIT_SHA.env && docker pull $IMAGE_TAG"
    - ssh dockeruser@$ssh_deploy_host 'docker logout'
    - ssh dockeruser@$ssh_deploy_host "latestHash=\"\$(git ls-remote https://$deployment_broker_user:$deployment_broker_pass@gitlab.com/rustblackhawk/blackhawk-deployment-broker.git HEAD | awk '{ print \$1}')\" && [ ! -e \"./deployments/\$latestHash\" ] && git clone https://$deployment_broker_user:$deployment_broker_pass@gitlab.com/rustblackhawk/blackhawk-deployment-broker.git \"./deployments/\$latestHash\" || echo \"No need to clone\" && chmod -R +x \"./deployments/\$latestHash/scripts/\""
    - ssh dockeruser@$ssh_deploy_host "source ./environment-$CI_COMMIT_SHA.env && latestHash=\"\$(git ls-remote https://$deployment_broker_user:$deployment_broker_pass@gitlab.com/rustblackhawk/blackhawk-deployment-broker.git HEAD | awk '{ print \$1}')\" && for service in \$(docker service ls --format \"{{.Name}}\" | grep \"blackhawk_rustserver\");do docker service scale -d \$service=0;done && for service in \$(docker service ls --format \"{{.Name}}\" | grep \"blackhawk_rustserver\");do while [ \"\$(docker service ps \$service --format \"{{.ID}}\")\" ];do sleep 5;done;done"
    - ssh dockeruser@$ssh_deploy_host "source ./environment-$CI_COMMIT_SHA.env && latestHash=\"\$(git ls-remote https://$deployment_broker_user:$deployment_broker_pass@gitlab.com/rustblackhawk/blackhawk-deployment-broker.git HEAD | awk '{ print \$1}')\" && ./deployments/\$latestHash/scripts/run.sh --use-stack --to='prod' --command='deploy --with-registry-auth $DEPLOY_STACK_NAME' --include-rust-server"
  after_script:
    - ssh dockeruser@$ssh_deploy_host "sleep 5"
    - ssh dockeruser@$ssh_deploy_host "rm -f ./environment-$CI_COMMIT_SHA.env"
    - rm -rf ~/.ssh
  only:
    - master
